version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: db
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CatBikes
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - dbdata:/var/lib/mysql
      - ./backend/sql/CatBikes.sql:/docker-entrypoint-initdb.d/datadump.sql
    networks:
      - project

  django:
    build: ./backend
    container_name: django
    command: sh -c '/wait-for-it.sh -t 0 db:3306 -- python ./manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - project

  react:
    build: ./frontend
    container_name: react
    ports:
      - "3000:3000"
    depends_on:
      - db
      - django
    networks:
      - project



volumes:
  dbdata:

networks:
  project: