# Generated by Django 4.1.6 on 2023-02-20 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blacklist2FA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist2fa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_2FA', to=settings.AUTH_USER_MODEL),
        ),
    ]
