# Generated by Django 4.1.6 on 2023-02-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist2FA', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blacklist',
            new_name='Blacklist2FA',
        ),
    ]
