# Generated by Django 4.1.6 on 2023-02-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokenForgotPassword',
            field=models.SlugField(editable=False, max_length=254, null=True, unique=True),
        ),
    ]
