# Generated by Django 4.1.6 on 2023-02-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_tokenforgotpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_register',
            field=models.CharField(max_length=30, null=True, verbose_name='type_register'),
        ),
    ]
