# Generated by Django 4.1.6 on 2023-02-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_type_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='countLogs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_2FA',
            field=models.BooleanField(default=False),
        ),
    ]
